name: Deploy

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  npm:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1
#      - name: Extract tag
#        id: extract_tag
#        run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
#      - uses: reedyuk/npm-version@1.2.2
#        with:
#          git-tag-version: false
#          version: ${{ steps.extract_tag.outputs.tag }}
      - uses: keloran/version-bump@main
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - name: Rollup
        run: bun run build
      - name: NPM
        run: npm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
